In [4]:
pip install ibm_watson_machine_learning

     |████████████████████████████████| 1.7 MB 5.0 MB/s 
     |████████████████████████████████| 51 kB 740 kB/s 
     |████████████████████████████████| 824 kB 51.5 MB/s 
     |████████████████████████████████| 133 kB 54.3 MB/s 
     |████████████████████████████████| 547 kB 43.1 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.7.0-py2.py3-none-any.whl size=72564 sha256=614ec5c682a4a38e740aba9afc8687c92517eee9ed15616f49a78d82a03dd417
  Stored in directory: /root/.cache/pip/wheels/47/22/bf/e1154ff0f5de93cc477acd0ca69abfbb8b799c5b28a66b44c2
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.7.0-py2.py3-none-any.whl size=501013 sha256=e9af9a8d1ccecea7f0243b165153b37849d2b7dffdbdaeebdf65b08f9c117f0a
  Stored in directory: /root/.cache/pip/wheels/6c/a2/e4/c16d02f809a3ea998e17cfd02c13369281f3d232aaf5902c19
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_sdk_s3transfer-2.7.0-py2.py3-none-any.whl size=88619 sha256=5cad600ea266c9729f70ae41d9134844f198eaa

In [5]:
from ibm_watson_machine_learning import APIClient
wml_credentials={"url":"https://eu-gb.ml.cloud.ibm.com",
                "apikey":"BCv3mSoW_qrApbYM8AyL460LVBYXtIXCgDPut6_r5Qii"}
client = APIClient(wml_credentials)

Python 3.7 and 3.8 frameworks are deprecated and will be removed in a future release. Use Python 3.9 framework instead.


In [6]:
client = APIClient(wml_credentials)

Python 3.7 and 3.8 frameworks are deprecated and will be removed in a future release. Use Python 3.9 framework instead.


In [9]:
def guid_space_name(client,space_name):
    space=client.spaces.get_details()
    return(next(item for item in space['resources'] if item['entity']["name"]==space_name)['metadata']['id'])

In [10]:
space_uid=guid_space_name(client,'EHDP')
print("space UID = "+space_uid)

space UID = c09b72a8-61fa-4417-9ed0-38205dad89e5


In [11]:
client.set.default_space(space_uid)

'SUCCESS'

In [12]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
runtime-22.1-py3.9             12b83a17-24d8-5082-900f-0ab31fbfd3cb  base
scikit-learn_0.22-py3.6        154010f

In [13]:
client.repository.download('75eea0e6-e19e-47b6-aff5-fb8891536dcd','dr.tar.gz')

Successfully saved model content to file: 'dr.tar.gz'


'/content/dr.tar.gz'

# Testing the IBM Model

In [16]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np

In [17]:
#load saved model file
model=load_model('IBM-Xception-diabetic-retinopathy.h5')

In [30]:
#load one random image from local system
img=image.load_img(r'3.png',target_size=(299,299))

In [31]:
import numpy as np
x= image.img_to_array(img)
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 299, 299, 3)

In [32]:
model.predict(img_data)

array([[5.70550853e-27, 1.04548146e-23, 9.09958331e-09, 9.85979378e-01,
        1.40205827e-02]], dtype=float32)

In [33]:
output=np.argmax(model.predict(img_data), axis=1)


In [34]:
output==0,output==1,output==2,output==3,output==4

(array([False]),
 array([False]),
 array([False]),
 array([ True]),
 array([False]))

In [35]:
index=['No Diabetic Retinopathy', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR']
result = str(index[output[0]])
result

'Severe DR'